<?php
/**
 * Created by PhpStorm.
 * User: carante
 * Date: 26/12/2016
 * Time: 19.17
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
}
